<?php

return [
    'NO_STAFF_ROLE'                 => [5],
    'SUPER_STAFF'                   => 5,
    'BAN_ATTEMPT'                   => 3,
    'HOUR_BAN'                      => 1,
    'PAGE_LIMIT'                    => 10,
    'PASSWORD_LENGTH'               => 12,
    'MAIL_AUTO_GO_EDU'              => 'testmrb1@golineglobal.vn',
    'GO_EDU_M'                      => '訪船管理システム',
    'BARCODE_LENGTH'                => 9,
    'REMEMBER_ME_EXPIRED_TIME'      => 43800,
    'MIN_AGE'                       => 5,
    'RESET_PASSWORD_EXPIRED_TIME'   => 60,
    'RANDOM_PASSWORD_LENGTH'        => 60,
    'DAYS_NEW_STUDENT'              => 30,
    'AVATAR_WIDTH'                  => 300,
    'AVATAR_HEIGHT'                 => 300,
    'IMAGE_QUALITY'                 => 90,
    'PROGRESS_PERCENTAGE'           => 100,
    'CHUNK_SIZE'                    => 1000,
    'DEFAULT_PAGE'                  => 1,
    'DEFAULT_PER_PAGE'              => 10,
    'RECENT_BOOKINGS_DEFAULT_LIMIT' => 10,
    'RECENT_BOOKINGS_MIN_LIMIT'     => 1,
    'RECENT_BOOKINGS_MAX_LIMIT'     => 100,
    'PERCENTAGE_MULTIPLIER'         => 100,
    'DECIMAL_PRECISION'             => 2,
    'TIME_TOKEN_CHECK_VERIFY_EMAIL' => 60,
    'ROLES'                         => [
        'ADMIN'   => 'admin',
        'PARTNER' => 'partner',
        'USER'    => 'user',
    ],
    'CLOUDINARY_MAX_IMAGE_SIZE' => 10 * 1024 * 1024,
    'CLOUDINARY_MAX_IMAGES' => 10,
    "CLOUDINARY_HEADER_IMAGE_URL" => "https://res.cloudinary.com/dyragzjcd/image/upload",
    'IMAGE_RESIZE_WIDTH' => 800,
    'WEBP_QUALITY' => 85,
    'IMAGE_TYPES' => [
        'OTHER' => 0,
        'MAIN_ROOM' => 1,
        'INTERIOR' => 2,
        'EXTERIOR' => 3,
        'BATHROOM' => 4,
        'KITCHEN' => 5,
        // OTHER TYPES
        'BALCONY' => 6,
        'LIVING_ROOM' => 7,
        'BEDROOM' => 8,
        'DINING_ROOM' => 9,
        'GARDEN' => 10,
        'PARKING' => 11,
        'ENTRANCE' => 12,
        'STAIRCASE' => 13,
        'HALLWAY' => 14,
        'OFFICE' => 15,
    ],
    "ERROR_VERIFY_EMAIL_TOKEN" => [
        "VET1" => "Email verification token is required.",
        "VET2" => "Email verification token is invalid.",
        "VET3" => "Email verification token has expired.",
        "VET4" => "Email verification token does not exist.",
        "VET5" => "Email has already been verified.",
        "VET6" => "Email verification successful.",
    ]

];
